server:
  port: 8181
spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    .repositories:
      bootstrap-mode: default
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

